# Generated by Django 4.2.1 on 2023-06-07 17:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Tytuł książki', max_length=70)),
                ('publication_date', models.DateField(verbose_name='Data publikacji książki')),
                ('number', models.CharField(max_length=20, verbose_name='Numer książki')),
            ],
        ),
        migrations.CreateModel(
            name='Contributor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_names', models.CharField(help_text='Imię współtwórcy', max_length=50)),
                ('last_names', models.CharField(help_text='Nazwisko współtwórcy', max_length=50)),
                ('email', models.EmailField(help_text='E-mail współtwórcy', max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Publisher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Nazwa wydawnictwa', max_length=50)),
                ('website', models.URLField(help_text='Witryna wydawnictwa')),
                ('email', models.EmailField(help_text='Adres e-mail wydawnictwa', max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(help_text='Tekst recenzji')),
                ('rating', models.IntegerField(help_text='Ocena uzytkownika')),
                ('date_created', models.DateTimeField(auto_now_add=True, help_text='Data i czas utworzenia recenzji')),
                ('date_edited', models.DateTimeField(help_text='Data i czas ostatniej edycji recenzji', null=True)),
                ('book', models.ForeignKey(help_text='Recenzowana książka', on_delete=django.db.models.deletion.CASCADE, to='reviews.book')),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='BookContributor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('AUTHOR', 'Author'), ('C0_AUTHOR', 'Co_Author'), ('EDITOR', 'Editor')], max_length=20, verbose_name='Rola:')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reviews.book')),
                ('contributor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reviews.contributor')),
            ],
        ),
        migrations.AddField(
            model_name='book',
            name='contributors',
            field=models.ManyToManyField(through='reviews.BookContributor', to='reviews.contributor'),
        ),
        migrations.AddField(
            model_name='book',
            name='publisher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reviews.publisher'),
        ),
    ]
