# Generated by Django 4.2.2 on 2023-06-12 18:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='number',
            new_name='isbn',
        ),
    ]
